### ISSUE TITLE
[Bug]: need fixed

### ISSUE THREAD

**Issue by William3Johnson** [snapcrafters/cassandra#9]
### What happened?

Need fixed 

### What should have happened?

Need fixed

### Output of `snap info $snap_name`

```shell
Need fixed
```

### Output of `snap connections $snap_name`

```shell
Need fixed
```

### Output of `snap version`

```shell
Need fixed
```

**Comment by athos-ribeiro** [comment]
Hi,

Was this unintended?

I am closing this. Feel free to re-open after properly editing the bug template!
